name: 'quest_kingdom'
version: '1.0.0'

profile: 'quest_kingdom'

model-paths: ["models"]
target-path: "target"
seed-paths: ["data"]
test-paths: ["tests"]

models:
  quest_kingdom:
    staging:
      +materialized: view
      
    marts:
      core:
        +materialized: table
      
      retention:
        +materialized: table